// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: node/node.proto

package node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node registration and heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PendingActions []string               `protobuf:"bytes,2,rep,name=pending_actions,json=pendingActions,proto3" json:"pending_actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetPendingActions() []string {
	if x != nil {
		return x.PendingActions
	}
	return nil
}

type NodeStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	State                string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // ready, draining, unhealthy
	CpuTotal             int32                  `protobuf:"varint,2,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuAllocated         int32                  `protobuf:"varint,3,opt,name=cpu_allocated,json=cpuAllocated,proto3" json:"cpu_allocated,omitempty"`
	MemoryTotalBytes     int64                  `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryAllocatedBytes int64                  `protobuf:"varint,5,opt,name=memory_allocated_bytes,json=memoryAllocatedBytes,proto3" json:"memory_allocated_bytes,omitempty"`
	SandboxCount         int32                  `protobuf:"varint,6,opt,name=sandbox_count,json=sandboxCount,proto3" json:"sandbox_count,omitempty"`
	CachedArtifacts      []string               `protobuf:"bytes,7,rep,name=cached_artifacts,json=cachedArtifacts,proto3" json:"cached_artifacts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_node_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeStatus) GetCpuTotal() int32 {
	if x != nil {
		return x.CpuTotal
	}
	return 0
}

func (x *NodeStatus) GetCpuAllocated() int32 {
	if x != nil {
		return x.CpuAllocated
	}
	return 0
}

func (x *NodeStatus) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeStatus) GetMemoryAllocatedBytes() int64 {
	if x != nil {
		return x.MemoryAllocatedBytes
	}
	return 0
}

func (x *NodeStatus) GetSandboxCount() int32 {
	if x != nil {
		return x.SandboxCount
	}
	return 0
}

func (x *NodeStatus) GetCachedArtifacts() []string {
	if x != nil {
		return x.CachedArtifacts
	}
	return nil
}

// Sandbox lifecycle
type CreateSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId        string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	CpuCount       int32                  `protobuf:"varint,4,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryMb       int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskSizeMb     int32                  `protobuf:"varint,6,opt,name=disk_size_mb,json=diskSizeMb,proto3" json:"disk_size_mb,omitempty"`
	EnvVars        map[string]string      `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	AutoPause      bool                   `protobuf:"varint,10,opt,name=auto_pause,json=autoPause,proto3" json:"auto_pause,omitempty"`
	EnvdToken      string                 `protobuf:"bytes,11,opt,name=envd_token,json=envdToken,proto3" json:"envd_token,omitempty"`
	ArtifactUrl    string                 `protobuf:"bytes,12,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"` // URL to download rootfs if not cached
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_node_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateSandboxRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CreateSandboxRequest) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *CreateSandboxRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateSandboxRequest) GetDiskSizeMb() int32 {
	if x != nil {
		return x.DiskSizeMb
	}
	return 0
}

func (x *CreateSandboxRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CreateSandboxRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSandboxRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateSandboxRequest) GetAutoPause() bool {
	if x != nil {
		return x.AutoPause
	}
	return false
}

func (x *CreateSandboxRequest) GetEnvdToken() string {
	if x != nil {
		return x.EnvdToken
	}
	return ""
}

func (x *CreateSandboxRequest) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EnvdAddress   string                 `protobuf:"bytes,3,opt,name=envd_address,json=envdAddress,proto3" json:"envd_address,omitempty"` // IP:port to reach envd
	EnvdPort      int32                  `protobuf:"varint,4,opt,name=envd_port,json=envdPort,proto3" json:"envd_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_node_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateSandboxResponse) GetEnvdAddress() string {
	if x != nil {
		return x.EnvdAddress
	}
	return ""
}

func (x *CreateSandboxResponse) GetEnvdPort() int32 {
	if x != nil {
		return x.EnvdPort
	}
	return 0
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_node_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{5}
}

func (x *StopSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StopSandboxRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_node_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{6}
}

func (x *StopSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PauseSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxRequest) Reset() {
	*x = PauseSandboxRequest{}
	mi := &file_node_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxRequest) ProtoMessage() {}

func (x *PauseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxRequest.ProtoReflect.Descriptor instead.
func (*PauseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{7}
}

func (x *PauseSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type PauseSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // For resuming later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxResponse) Reset() {
	*x = PauseSandboxResponse{}
	mi := &file_node_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxResponse) ProtoMessage() {}

func (x *PauseSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxResponse.ProtoReflect.Descriptor instead.
func (*PauseSandboxResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{8}
}

func (x *PauseSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PauseSandboxResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ResumeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_node_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ResumeSandboxRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ResumeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EnvdAddress   string                 `protobuf:"bytes,3,opt,name=envd_address,json=envdAddress,proto3" json:"envd_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxResponse) Reset() {
	*x = ResumeSandboxResponse{}
	mi := &file_node_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxResponse) ProtoMessage() {}

func (x *ResumeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxResponse.ProtoReflect.Descriptor instead.
func (*ResumeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResumeSandboxResponse) GetEnvdAddress() string {
	if x != nil {
		return x.EnvdAddress
	}
	return ""
}

type GetSandboxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusRequest) Reset() {
	*x = GetSandboxStatusRequest{}
	mi := &file_node_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusRequest) ProtoMessage() {}

func (x *GetSandboxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{11}
}

func (x *GetSandboxStatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Sandbox       *SandboxInfo           `protobuf:"bytes,2,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusResponse) Reset() {
	*x = GetSandboxStatusResponse{}
	mi := &file_node_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusResponse) ProtoMessage() {}

func (x *GetSandboxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{12}
}

func (x *GetSandboxStatusResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetSandboxStatusResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_node_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{13}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_node_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{14}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // starting, running, paused, stopped, error
	EnvdAddress   string                 `protobuf:"bytes,5,opt,name=envd_address,json=envdAddress,proto3" json:"envd_address,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CpuCount      int32                  `protobuf:"varint,8,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,9,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_node_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{15}
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxInfo) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SandboxInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SandboxInfo) GetEnvdAddress() string {
	if x != nil {
		return x.EnvdAddress
	}
	return ""
}

func (x *SandboxInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *SandboxInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SandboxInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *SandboxInfo) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *SandboxInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Artifact management
type PullArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ArtifactUrl   string                 `protobuf:"bytes,3,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullArtifactRequest) Reset() {
	*x = PullArtifactRequest{}
	mi := &file_node_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullArtifactRequest) ProtoMessage() {}

func (x *PullArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullArtifactRequest.ProtoReflect.Descriptor instead.
func (*PullArtifactRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{16}
}

func (x *PullArtifactRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *PullArtifactRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *PullArtifactRequest) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

type PullArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LocalPath     string                 `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullArtifactResponse) Reset() {
	*x = PullArtifactResponse{}
	mi := &file_node_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullArtifactResponse) ProtoMessage() {}

func (x *PullArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullArtifactResponse.ProtoReflect.Descriptor instead.
func (*PullArtifactResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{17}
}

func (x *PullArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PullArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PullArtifactResponse) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

// Debugging
type ExecCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandRequest) Reset() {
	*x = ExecCommandRequest{}
	mi := &file_node_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandRequest) ProtoMessage() {}

func (x *ExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{18}
}

func (x *ExecCommandRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ExecCommandResponse_Stdout
	//	*ExecCommandResponse_Stderr
	//	*ExecCommandResponse_ExitCode
	Output        isExecCommandResponse_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandResponse) Reset() {
	*x = ExecCommandResponse{}
	mi := &file_node_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandResponse) ProtoMessage() {}

func (x *ExecCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecCommandResponse) Descriptor() ([]byte, []int) {
	return file_node_node_proto_rawDescGZIP(), []int{19}
}

func (x *ExecCommandResponse) GetOutput() isExecCommandResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecCommandResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecCommandResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecCommandResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecCommandResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecCommandResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*ExecCommandResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecCommandResponse_Output interface {
	isExecCommandResponse_Output()
}

type ExecCommandResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecCommandResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecCommandResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecCommandResponse_Stdout) isExecCommandResponse_Output() {}

func (*ExecCommandResponse_Stderr) isExecCommandResponse_Output() {}

func (*ExecCommandResponse_ExitCode) isExecCommandResponse_Output() {}

var File_node_node_proto protoreflect.FileDescriptor

const file_node_node_proto_rawDesc = "" +
	"\n" +
	"\x0fnode/node.proto\x12\x04node\"U\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.node.NodeStatusR\x06status\"`\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12'\n" +
	"\x0fpending_actions\x18\x02 \x03(\tR\x0ependingActions\"\x98\x02\n" +
	"\n" +
	"NodeStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tcpu_total\x18\x02 \x01(\x05R\bcpuTotal\x12#\n" +
	"\rcpu_allocated\x18\x03 \x01(\x05R\fcpuAllocated\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x124\n" +
	"\x16memory_allocated_bytes\x18\x05 \x01(\x03R\x14memoryAllocatedBytes\x12#\n" +
	"\rsandbox_count\x18\x06 \x01(\x05R\fsandboxCount\x12)\n" +
	"\x10cached_artifacts\x18\a \x03(\tR\x0fcachedArtifacts\"\xda\x04\n" +
	"\x14CreateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12\x1b\n" +
	"\tcpu_count\x18\x04 \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12 \n" +
	"\fdisk_size_mb\x18\x06 \x01(\x05R\n" +
	"diskSizeMb\x12B\n" +
	"\benv_vars\x18\a \x03(\v2'.node.CreateSandboxRequest.EnvVarsEntryR\aenvVars\x12D\n" +
	"\bmetadata\x18\b \x03(\v2(.node.CreateSandboxRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\x03R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"auto_pause\x18\n" +
	" \x01(\bR\tautoPause\x12\x1d\n" +
	"\n" +
	"envd_token\x18\v \x01(\tR\tenvdToken\x12!\n" +
	"\fartifact_url\x18\f \x01(\tR\vartifactUrl\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x15CreateSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\fenvd_address\x18\x03 \x01(\tR\venvdAddress\x12\x1b\n" +
	"\tenvd_port\x18\x04 \x01(\x05R\benvdPort\"I\n" +
	"\x12StopSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"E\n" +
	"\x13StopSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\x13PauseSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"g\n" +
	"\x14PauseSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\"V\n" +
	"\x14ResumeSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"j\n" +
	"\x15ResumeSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\fenvd_address\x18\x03 \x01(\tR\venvdAddress\"8\n" +
	"\x17GetSandboxStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"_\n" +
	"\x18GetSandboxStatusResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12+\n" +
	"\asandbox\x18\x02 \x01(\v2\x11.node.SandboxInfoR\asandbox\"\x16\n" +
	"\x14ListSandboxesRequest\"H\n" +
	"\x15ListSandboxesResponse\x12/\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x11.node.SandboxInfoR\tsandboxes\"\xaf\x02\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12!\n" +
	"\fenvd_address\x18\x05 \x01(\tR\venvdAddress\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\tcpu_count\x18\b \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\t \x01(\x05R\bmemoryMb\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"t\n" +
	"\x13PullArtifactRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12!\n" +
	"\fartifact_url\x18\x03 \x01(\tR\vartifactUrl\"e\n" +
	"\x14PullArtifactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\"a\n" +
	"\x12ExecCommandRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"r\n" +
	"\x13ExecCommandResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\b\n" +
	"\x06output2\x92\x05\n" +
	"\tNodeAgent\x12<\n" +
	"\tHeartbeat\x12\x16.node.HeartbeatRequest\x1a\x17.node.HeartbeatResponse\x12H\n" +
	"\rCreateSandbox\x12\x1a.node.CreateSandboxRequest\x1a\x1b.node.CreateSandboxResponse\x12B\n" +
	"\vStopSandbox\x12\x18.node.StopSandboxRequest\x1a\x19.node.StopSandboxResponse\x12E\n" +
	"\fPauseSandbox\x12\x19.node.PauseSandboxRequest\x1a\x1a.node.PauseSandboxResponse\x12H\n" +
	"\rResumeSandbox\x12\x1a.node.ResumeSandboxRequest\x1a\x1b.node.ResumeSandboxResponse\x12Q\n" +
	"\x10GetSandboxStatus\x12\x1d.node.GetSandboxStatusRequest\x1a\x1e.node.GetSandboxStatusResponse\x12H\n" +
	"\rListSandboxes\x12\x1a.node.ListSandboxesRequest\x1a\x1b.node.ListSandboxesResponse\x12E\n" +
	"\fPullArtifact\x12\x19.node.PullArtifactRequest\x1a\x1a.node.PullArtifactResponse\x12D\n" +
	"\vExecCommand\x12\x18.node.ExecCommandRequest\x1a\x19.node.ExecCommandResponse0\x01Bq\n" +
	"\bcom.nodeB\tNodeProtoP\x01Z*github.com/0prodigy/OpenE2B/pkg/proto/node\xa2\x02\x03NXX\xaa\x02\x04Node\xca\x02\x04Node\xe2\x02\x10Node\\GPBMetadata\xea\x02\x04Nodeb\x06proto3"

var (
	file_node_node_proto_rawDescOnce sync.Once
	file_node_node_proto_rawDescData []byte
)

func file_node_node_proto_rawDescGZIP() []byte {
	file_node_node_proto_rawDescOnce.Do(func() {
		file_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_node_proto_rawDesc), len(file_node_node_proto_rawDesc)))
	})
	return file_node_node_proto_rawDescData
}

var file_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_node_node_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),         // 0: node.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 1: node.HeartbeatResponse
	(*NodeStatus)(nil),               // 2: node.NodeStatus
	(*CreateSandboxRequest)(nil),     // 3: node.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),    // 4: node.CreateSandboxResponse
	(*StopSandboxRequest)(nil),       // 5: node.StopSandboxRequest
	(*StopSandboxResponse)(nil),      // 6: node.StopSandboxResponse
	(*PauseSandboxRequest)(nil),      // 7: node.PauseSandboxRequest
	(*PauseSandboxResponse)(nil),     // 8: node.PauseSandboxResponse
	(*ResumeSandboxRequest)(nil),     // 9: node.ResumeSandboxRequest
	(*ResumeSandboxResponse)(nil),    // 10: node.ResumeSandboxResponse
	(*GetSandboxStatusRequest)(nil),  // 11: node.GetSandboxStatusRequest
	(*GetSandboxStatusResponse)(nil), // 12: node.GetSandboxStatusResponse
	(*ListSandboxesRequest)(nil),     // 13: node.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),    // 14: node.ListSandboxesResponse
	(*SandboxInfo)(nil),              // 15: node.SandboxInfo
	(*PullArtifactRequest)(nil),      // 16: node.PullArtifactRequest
	(*PullArtifactResponse)(nil),     // 17: node.PullArtifactResponse
	(*ExecCommandRequest)(nil),       // 18: node.ExecCommandRequest
	(*ExecCommandResponse)(nil),      // 19: node.ExecCommandResponse
	nil,                              // 20: node.CreateSandboxRequest.EnvVarsEntry
	nil,                              // 21: node.CreateSandboxRequest.MetadataEntry
}
var file_node_node_proto_depIdxs = []int32{
	2,  // 0: node.HeartbeatRequest.status:type_name -> node.NodeStatus
	20, // 1: node.CreateSandboxRequest.env_vars:type_name -> node.CreateSandboxRequest.EnvVarsEntry
	21, // 2: node.CreateSandboxRequest.metadata:type_name -> node.CreateSandboxRequest.MetadataEntry
	15, // 3: node.GetSandboxStatusResponse.sandbox:type_name -> node.SandboxInfo
	15, // 4: node.ListSandboxesResponse.sandboxes:type_name -> node.SandboxInfo
	0,  // 5: node.NodeAgent.Heartbeat:input_type -> node.HeartbeatRequest
	3,  // 6: node.NodeAgent.CreateSandbox:input_type -> node.CreateSandboxRequest
	5,  // 7: node.NodeAgent.StopSandbox:input_type -> node.StopSandboxRequest
	7,  // 8: node.NodeAgent.PauseSandbox:input_type -> node.PauseSandboxRequest
	9,  // 9: node.NodeAgent.ResumeSandbox:input_type -> node.ResumeSandboxRequest
	11, // 10: node.NodeAgent.GetSandboxStatus:input_type -> node.GetSandboxStatusRequest
	13, // 11: node.NodeAgent.ListSandboxes:input_type -> node.ListSandboxesRequest
	16, // 12: node.NodeAgent.PullArtifact:input_type -> node.PullArtifactRequest
	18, // 13: node.NodeAgent.ExecCommand:input_type -> node.ExecCommandRequest
	1,  // 14: node.NodeAgent.Heartbeat:output_type -> node.HeartbeatResponse
	4,  // 15: node.NodeAgent.CreateSandbox:output_type -> node.CreateSandboxResponse
	6,  // 16: node.NodeAgent.StopSandbox:output_type -> node.StopSandboxResponse
	8,  // 17: node.NodeAgent.PauseSandbox:output_type -> node.PauseSandboxResponse
	10, // 18: node.NodeAgent.ResumeSandbox:output_type -> node.ResumeSandboxResponse
	12, // 19: node.NodeAgent.GetSandboxStatus:output_type -> node.GetSandboxStatusResponse
	14, // 20: node.NodeAgent.ListSandboxes:output_type -> node.ListSandboxesResponse
	17, // 21: node.NodeAgent.PullArtifact:output_type -> node.PullArtifactResponse
	19, // 22: node.NodeAgent.ExecCommand:output_type -> node.ExecCommandResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_node_node_proto_init() }
func file_node_node_proto_init() {
	if File_node_node_proto != nil {
		return
	}
	file_node_node_proto_msgTypes[19].OneofWrappers = []any{
		(*ExecCommandResponse_Stdout)(nil),
		(*ExecCommandResponse_Stderr)(nil),
		(*ExecCommandResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_node_proto_rawDesc), len(file_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_node_proto_goTypes,
		DependencyIndexes: file_node_node_proto_depIdxs,
		MessageInfos:      file_node_node_proto_msgTypes,
	}.Build()
	File_node_node_proto = out.File
	file_node_node_proto_goTypes = nil
	file_node_node_proto_depIdxs = nil
}
