// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: node/node.proto

package nodeconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	node "github.com/0prodigy/OpenE2B/pkg/proto/node"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeAgentName is the fully-qualified name of the NodeAgent service.
	NodeAgentName = "node.NodeAgent"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeAgentHeartbeatProcedure is the fully-qualified name of the NodeAgent's Heartbeat RPC.
	NodeAgentHeartbeatProcedure = "/node.NodeAgent/Heartbeat"
	// NodeAgentCreateSandboxProcedure is the fully-qualified name of the NodeAgent's CreateSandbox RPC.
	NodeAgentCreateSandboxProcedure = "/node.NodeAgent/CreateSandbox"
	// NodeAgentStopSandboxProcedure is the fully-qualified name of the NodeAgent's StopSandbox RPC.
	NodeAgentStopSandboxProcedure = "/node.NodeAgent/StopSandbox"
	// NodeAgentPauseSandboxProcedure is the fully-qualified name of the NodeAgent's PauseSandbox RPC.
	NodeAgentPauseSandboxProcedure = "/node.NodeAgent/PauseSandbox"
	// NodeAgentResumeSandboxProcedure is the fully-qualified name of the NodeAgent's ResumeSandbox RPC.
	NodeAgentResumeSandboxProcedure = "/node.NodeAgent/ResumeSandbox"
	// NodeAgentGetSandboxStatusProcedure is the fully-qualified name of the NodeAgent's
	// GetSandboxStatus RPC.
	NodeAgentGetSandboxStatusProcedure = "/node.NodeAgent/GetSandboxStatus"
	// NodeAgentListSandboxesProcedure is the fully-qualified name of the NodeAgent's ListSandboxes RPC.
	NodeAgentListSandboxesProcedure = "/node.NodeAgent/ListSandboxes"
	// NodeAgentPullArtifactProcedure is the fully-qualified name of the NodeAgent's PullArtifact RPC.
	NodeAgentPullArtifactProcedure = "/node.NodeAgent/PullArtifact"
	// NodeAgentExecCommandProcedure is the fully-qualified name of the NodeAgent's ExecCommand RPC.
	NodeAgentExecCommandProcedure = "/node.NodeAgent/ExecCommand"
)

// NodeAgentClient is a client for the node.NodeAgent service.
type NodeAgentClient interface {
	// Heartbeat reports node status to control plane
	Heartbeat(context.Context, *connect.Request[node.HeartbeatRequest]) (*connect.Response[node.HeartbeatResponse], error)
	// CreateSandbox creates a new sandbox on this node
	CreateSandbox(context.Context, *connect.Request[node.CreateSandboxRequest]) (*connect.Response[node.CreateSandboxResponse], error)
	// StopSandbox terminates a sandbox
	StopSandbox(context.Context, *connect.Request[node.StopSandboxRequest]) (*connect.Response[node.StopSandboxResponse], error)
	// PauseSandbox pauses a sandbox
	PauseSandbox(context.Context, *connect.Request[node.PauseSandboxRequest]) (*connect.Response[node.PauseSandboxResponse], error)
	// ResumeSandbox resumes a paused sandbox
	ResumeSandbox(context.Context, *connect.Request[node.ResumeSandboxRequest]) (*connect.Response[node.ResumeSandboxResponse], error)
	// GetSandboxStatus returns the current status of a sandbox
	GetSandboxStatus(context.Context, *connect.Request[node.GetSandboxStatusRequest]) (*connect.Response[node.GetSandboxStatusResponse], error)
	// ListSandboxes returns all sandboxes on this node
	ListSandboxes(context.Context, *connect.Request[node.ListSandboxesRequest]) (*connect.Response[node.ListSandboxesResponse], error)
	// PullArtifact downloads and prepares a template artifact
	PullArtifact(context.Context, *connect.Request[node.PullArtifactRequest]) (*connect.Response[node.PullArtifactResponse], error)
	// ExecCommand executes a command in a sandbox (for debugging)
	ExecCommand(context.Context, *connect.Request[node.ExecCommandRequest]) (*connect.ServerStreamForClient[node.ExecCommandResponse], error)
}

// NewNodeAgentClient constructs a client for the node.NodeAgent service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeAgentClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeAgentClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeAgentMethods := node.File_node_node_proto.Services().ByName("NodeAgent").Methods()
	return &nodeAgentClient{
		heartbeat: connect.NewClient[node.HeartbeatRequest, node.HeartbeatResponse](
			httpClient,
			baseURL+NodeAgentHeartbeatProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		createSandbox: connect.NewClient[node.CreateSandboxRequest, node.CreateSandboxResponse](
			httpClient,
			baseURL+NodeAgentCreateSandboxProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("CreateSandbox")),
			connect.WithClientOptions(opts...),
		),
		stopSandbox: connect.NewClient[node.StopSandboxRequest, node.StopSandboxResponse](
			httpClient,
			baseURL+NodeAgentStopSandboxProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("StopSandbox")),
			connect.WithClientOptions(opts...),
		),
		pauseSandbox: connect.NewClient[node.PauseSandboxRequest, node.PauseSandboxResponse](
			httpClient,
			baseURL+NodeAgentPauseSandboxProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("PauseSandbox")),
			connect.WithClientOptions(opts...),
		),
		resumeSandbox: connect.NewClient[node.ResumeSandboxRequest, node.ResumeSandboxResponse](
			httpClient,
			baseURL+NodeAgentResumeSandboxProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("ResumeSandbox")),
			connect.WithClientOptions(opts...),
		),
		getSandboxStatus: connect.NewClient[node.GetSandboxStatusRequest, node.GetSandboxStatusResponse](
			httpClient,
			baseURL+NodeAgentGetSandboxStatusProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("GetSandboxStatus")),
			connect.WithClientOptions(opts...),
		),
		listSandboxes: connect.NewClient[node.ListSandboxesRequest, node.ListSandboxesResponse](
			httpClient,
			baseURL+NodeAgentListSandboxesProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("ListSandboxes")),
			connect.WithClientOptions(opts...),
		),
		pullArtifact: connect.NewClient[node.PullArtifactRequest, node.PullArtifactResponse](
			httpClient,
			baseURL+NodeAgentPullArtifactProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("PullArtifact")),
			connect.WithClientOptions(opts...),
		),
		execCommand: connect.NewClient[node.ExecCommandRequest, node.ExecCommandResponse](
			httpClient,
			baseURL+NodeAgentExecCommandProcedure,
			connect.WithSchema(nodeAgentMethods.ByName("ExecCommand")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeAgentClient implements NodeAgentClient.
type nodeAgentClient struct {
	heartbeat        *connect.Client[node.HeartbeatRequest, node.HeartbeatResponse]
	createSandbox    *connect.Client[node.CreateSandboxRequest, node.CreateSandboxResponse]
	stopSandbox      *connect.Client[node.StopSandboxRequest, node.StopSandboxResponse]
	pauseSandbox     *connect.Client[node.PauseSandboxRequest, node.PauseSandboxResponse]
	resumeSandbox    *connect.Client[node.ResumeSandboxRequest, node.ResumeSandboxResponse]
	getSandboxStatus *connect.Client[node.GetSandboxStatusRequest, node.GetSandboxStatusResponse]
	listSandboxes    *connect.Client[node.ListSandboxesRequest, node.ListSandboxesResponse]
	pullArtifact     *connect.Client[node.PullArtifactRequest, node.PullArtifactResponse]
	execCommand      *connect.Client[node.ExecCommandRequest, node.ExecCommandResponse]
}

// Heartbeat calls node.NodeAgent.Heartbeat.
func (c *nodeAgentClient) Heartbeat(ctx context.Context, req *connect.Request[node.HeartbeatRequest]) (*connect.Response[node.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// CreateSandbox calls node.NodeAgent.CreateSandbox.
func (c *nodeAgentClient) CreateSandbox(ctx context.Context, req *connect.Request[node.CreateSandboxRequest]) (*connect.Response[node.CreateSandboxResponse], error) {
	return c.createSandbox.CallUnary(ctx, req)
}

// StopSandbox calls node.NodeAgent.StopSandbox.
func (c *nodeAgentClient) StopSandbox(ctx context.Context, req *connect.Request[node.StopSandboxRequest]) (*connect.Response[node.StopSandboxResponse], error) {
	return c.stopSandbox.CallUnary(ctx, req)
}

// PauseSandbox calls node.NodeAgent.PauseSandbox.
func (c *nodeAgentClient) PauseSandbox(ctx context.Context, req *connect.Request[node.PauseSandboxRequest]) (*connect.Response[node.PauseSandboxResponse], error) {
	return c.pauseSandbox.CallUnary(ctx, req)
}

// ResumeSandbox calls node.NodeAgent.ResumeSandbox.
func (c *nodeAgentClient) ResumeSandbox(ctx context.Context, req *connect.Request[node.ResumeSandboxRequest]) (*connect.Response[node.ResumeSandboxResponse], error) {
	return c.resumeSandbox.CallUnary(ctx, req)
}

// GetSandboxStatus calls node.NodeAgent.GetSandboxStatus.
func (c *nodeAgentClient) GetSandboxStatus(ctx context.Context, req *connect.Request[node.GetSandboxStatusRequest]) (*connect.Response[node.GetSandboxStatusResponse], error) {
	return c.getSandboxStatus.CallUnary(ctx, req)
}

// ListSandboxes calls node.NodeAgent.ListSandboxes.
func (c *nodeAgentClient) ListSandboxes(ctx context.Context, req *connect.Request[node.ListSandboxesRequest]) (*connect.Response[node.ListSandboxesResponse], error) {
	return c.listSandboxes.CallUnary(ctx, req)
}

// PullArtifact calls node.NodeAgent.PullArtifact.
func (c *nodeAgentClient) PullArtifact(ctx context.Context, req *connect.Request[node.PullArtifactRequest]) (*connect.Response[node.PullArtifactResponse], error) {
	return c.pullArtifact.CallUnary(ctx, req)
}

// ExecCommand calls node.NodeAgent.ExecCommand.
func (c *nodeAgentClient) ExecCommand(ctx context.Context, req *connect.Request[node.ExecCommandRequest]) (*connect.ServerStreamForClient[node.ExecCommandResponse], error) {
	return c.execCommand.CallServerStream(ctx, req)
}

// NodeAgentHandler is an implementation of the node.NodeAgent service.
type NodeAgentHandler interface {
	// Heartbeat reports node status to control plane
	Heartbeat(context.Context, *connect.Request[node.HeartbeatRequest]) (*connect.Response[node.HeartbeatResponse], error)
	// CreateSandbox creates a new sandbox on this node
	CreateSandbox(context.Context, *connect.Request[node.CreateSandboxRequest]) (*connect.Response[node.CreateSandboxResponse], error)
	// StopSandbox terminates a sandbox
	StopSandbox(context.Context, *connect.Request[node.StopSandboxRequest]) (*connect.Response[node.StopSandboxResponse], error)
	// PauseSandbox pauses a sandbox
	PauseSandbox(context.Context, *connect.Request[node.PauseSandboxRequest]) (*connect.Response[node.PauseSandboxResponse], error)
	// ResumeSandbox resumes a paused sandbox
	ResumeSandbox(context.Context, *connect.Request[node.ResumeSandboxRequest]) (*connect.Response[node.ResumeSandboxResponse], error)
	// GetSandboxStatus returns the current status of a sandbox
	GetSandboxStatus(context.Context, *connect.Request[node.GetSandboxStatusRequest]) (*connect.Response[node.GetSandboxStatusResponse], error)
	// ListSandboxes returns all sandboxes on this node
	ListSandboxes(context.Context, *connect.Request[node.ListSandboxesRequest]) (*connect.Response[node.ListSandboxesResponse], error)
	// PullArtifact downloads and prepares a template artifact
	PullArtifact(context.Context, *connect.Request[node.PullArtifactRequest]) (*connect.Response[node.PullArtifactResponse], error)
	// ExecCommand executes a command in a sandbox (for debugging)
	ExecCommand(context.Context, *connect.Request[node.ExecCommandRequest], *connect.ServerStream[node.ExecCommandResponse]) error
}

// NewNodeAgentHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeAgentHandler(svc NodeAgentHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeAgentMethods := node.File_node_node_proto.Services().ByName("NodeAgent").Methods()
	nodeAgentHeartbeatHandler := connect.NewUnaryHandler(
		NodeAgentHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(nodeAgentMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentCreateSandboxHandler := connect.NewUnaryHandler(
		NodeAgentCreateSandboxProcedure,
		svc.CreateSandbox,
		connect.WithSchema(nodeAgentMethods.ByName("CreateSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentStopSandboxHandler := connect.NewUnaryHandler(
		NodeAgentStopSandboxProcedure,
		svc.StopSandbox,
		connect.WithSchema(nodeAgentMethods.ByName("StopSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentPauseSandboxHandler := connect.NewUnaryHandler(
		NodeAgentPauseSandboxProcedure,
		svc.PauseSandbox,
		connect.WithSchema(nodeAgentMethods.ByName("PauseSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentResumeSandboxHandler := connect.NewUnaryHandler(
		NodeAgentResumeSandboxProcedure,
		svc.ResumeSandbox,
		connect.WithSchema(nodeAgentMethods.ByName("ResumeSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentGetSandboxStatusHandler := connect.NewUnaryHandler(
		NodeAgentGetSandboxStatusProcedure,
		svc.GetSandboxStatus,
		connect.WithSchema(nodeAgentMethods.ByName("GetSandboxStatus")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentListSandboxesHandler := connect.NewUnaryHandler(
		NodeAgentListSandboxesProcedure,
		svc.ListSandboxes,
		connect.WithSchema(nodeAgentMethods.ByName("ListSandboxes")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentPullArtifactHandler := connect.NewUnaryHandler(
		NodeAgentPullArtifactProcedure,
		svc.PullArtifact,
		connect.WithSchema(nodeAgentMethods.ByName("PullArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	nodeAgentExecCommandHandler := connect.NewServerStreamHandler(
		NodeAgentExecCommandProcedure,
		svc.ExecCommand,
		connect.WithSchema(nodeAgentMethods.ByName("ExecCommand")),
		connect.WithHandlerOptions(opts...),
	)
	return "/node.NodeAgent/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeAgentHeartbeatProcedure:
			nodeAgentHeartbeatHandler.ServeHTTP(w, r)
		case NodeAgentCreateSandboxProcedure:
			nodeAgentCreateSandboxHandler.ServeHTTP(w, r)
		case NodeAgentStopSandboxProcedure:
			nodeAgentStopSandboxHandler.ServeHTTP(w, r)
		case NodeAgentPauseSandboxProcedure:
			nodeAgentPauseSandboxHandler.ServeHTTP(w, r)
		case NodeAgentResumeSandboxProcedure:
			nodeAgentResumeSandboxHandler.ServeHTTP(w, r)
		case NodeAgentGetSandboxStatusProcedure:
			nodeAgentGetSandboxStatusHandler.ServeHTTP(w, r)
		case NodeAgentListSandboxesProcedure:
			nodeAgentListSandboxesHandler.ServeHTTP(w, r)
		case NodeAgentPullArtifactProcedure:
			nodeAgentPullArtifactHandler.ServeHTTP(w, r)
		case NodeAgentExecCommandProcedure:
			nodeAgentExecCommandHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeAgentHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeAgentHandler struct{}

func (UnimplementedNodeAgentHandler) Heartbeat(context.Context, *connect.Request[node.HeartbeatRequest]) (*connect.Response[node.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.Heartbeat is not implemented"))
}

func (UnimplementedNodeAgentHandler) CreateSandbox(context.Context, *connect.Request[node.CreateSandboxRequest]) (*connect.Response[node.CreateSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.CreateSandbox is not implemented"))
}

func (UnimplementedNodeAgentHandler) StopSandbox(context.Context, *connect.Request[node.StopSandboxRequest]) (*connect.Response[node.StopSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.StopSandbox is not implemented"))
}

func (UnimplementedNodeAgentHandler) PauseSandbox(context.Context, *connect.Request[node.PauseSandboxRequest]) (*connect.Response[node.PauseSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.PauseSandbox is not implemented"))
}

func (UnimplementedNodeAgentHandler) ResumeSandbox(context.Context, *connect.Request[node.ResumeSandboxRequest]) (*connect.Response[node.ResumeSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.ResumeSandbox is not implemented"))
}

func (UnimplementedNodeAgentHandler) GetSandboxStatus(context.Context, *connect.Request[node.GetSandboxStatusRequest]) (*connect.Response[node.GetSandboxStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.GetSandboxStatus is not implemented"))
}

func (UnimplementedNodeAgentHandler) ListSandboxes(context.Context, *connect.Request[node.ListSandboxesRequest]) (*connect.Response[node.ListSandboxesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.ListSandboxes is not implemented"))
}

func (UnimplementedNodeAgentHandler) PullArtifact(context.Context, *connect.Request[node.PullArtifactRequest]) (*connect.Response[node.PullArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.PullArtifact is not implemented"))
}

func (UnimplementedNodeAgentHandler) ExecCommand(context.Context, *connect.Request[node.ExecCommandRequest], *connect.ServerStream[node.ExecCommandResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("node.NodeAgent.ExecCommand is not implemented"))
}
